# Generated by Django 2.2.7 on 2020-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contant',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
