# Generated by Django 3.0.8 on 2020-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('tag_line', models.CharField(max_length=200, verbose_name='TagLine')),
                ('title1', models.CharField(max_length=100, verbose_name='Title Of First Block')),
                ('content1', models.TextField(verbose_name='Content Of First Block')),
                ('title2', models.CharField(max_length=100, verbose_name='Title Of Second Block')),
                ('content2', models.TextField(verbose_name='Content Of Second Block')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
