# Generated by Django 2.2.7 on 2020-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile',
            field=models.ImageField(default='', upload_to='', verbose_name='Profile Image'),
            preserve_default=False,
        ),
    ]
